export const currentStudentInitState = {
  email: '',
  mobile: '',
  schoolYear: '',
  gradeLevelToEnroll: '11',
  withLRN: true,
  isReturnee: false,

  isPsaAvailable: true,
  psaBirthCertificateNo: '',
  learnerReferenceNo: '',
  lastName: '',
  firstName: '',
  middleName: '',
  extensionName: '',
  birthDate: '',
  sex: '',
  age: '',
  placeOfBirth: '',
  motherTongue: '',
  isIndigenousPeople: false,
  indigenousPeople: '',
  isFourPsBeneficiary: false,
  fourPsHouseHoldId: '',

  currentHouseNoStreet: '',
  currentStreetName: '',
  currentBarangay: '',
  currentMunicipalityCity: '',
  currentProvince: '',
  currentCountry: '',
  currentZipCode: '',
  isSameAsCurrentAddress: true,
  houseNoStreet: '',
  streetName: '',
  barangay: '',
  municipalityCity: '',
  province: '',
  country: '',
  zipCode: '',
};
