export const currentStudentInitState = {
  email: '',
  mobile: '',
  schoolYear: '',
  gradeLevelToEnroll: '11',
  withLRN: true,
  isReturnee: false,

  isPsaAvailable: true,
  psaBirthCertificateNo: '',
  learnerReferenceNo: '',
  lastName: '',
  firstName: '',
  middleName: '',
  extensionName: '',
  birthDate: '',
  sex: '',
  age: '',
  placeOfBirth: '',
  motherTongue: '',
  isIndigenousPeople: false,
  indigenousPeople: '',
  isFourPsBeneficiary: false,
  fourPsHouseHoldId: '',

  currentHouseNoStreet: '',
  currentStreetName: '',
  currentBarangay: '',
  currentMunicipalityCity: '',
  currentProvince: '',
  currentCountry: '',
  currentZipCode: '',
  isSameAsCurrentAddress: true,
  houseNoStreet: '',
  streetName: '',
  barangay: '',
  municipalityCity: '',
  province: '',
  country: '',
  zipCode: '',

  father: {
    lastName: '',
    firstName: '',
    middleName: '',
    contactNumber: '',
    email: '',
  },
  mother: {
    lastName: '',
    firstName: '',
    middleName: '',
    contactNumber: '',
    email: '',
  },
  guardian: {
    lastName: '',
    firstName: '',
    middleName: '',
    contactNumber: '',
    email: '',
  },

  returningLearner: {
    lastGradeLevelCompleted: '',
    lastSchoolYearCompleted: '',
    lastSchoolAttended: '',
    schoolID: '',
  },

  seniorHighSchool: {
    semester: '1st Sem',
    track: '',
    strand: '',
  },

  preferredDistanceLearningModalities: {
    isModularPrint: false,
    isOnline: false,
    isRadioBased: false,
    isBlended: false,
    isModularDigital: false,
    isEducationTV: false,
    isHomeschooling: false,
    isFaceToFace: false,
  },

  ncPasser: {
    isNcPasser: false,
    certificateNo: '',
    specialization: '',
    validUntil: '',
  },

  hsCompleter: {
    isHsCompleter: false,
    genAve: '',
    graduationDate: '',
    schoolAddress: '',
  },
  jhsCompleter: {
    isJhsCompleter: false,
    genAve: '',
    graduationDate: '',
    schoolAddress: '',
  },
  peptPasser: {
    isPeptPasser: false,
    examDate: '',
    learningCenterName: '',
    learningCenterAddress: '',
  },
  alsPasser: {
    isAlsPasser: false,
    examDate: '',
    learningCenterName: '',
    learningCenterAddress: '',
  },
  otherExams: {
    isOtherExamPasser: false,
    examType: '',
    examDate: '',
    learningCenterName: '',
    learningCenterAddress: '',
  },

  weightKg: 0,
  heightM: 0,
};
