const tracks = [
  {
    name: "Academic Track",
    strands: [
      {
        name: "Accountancy, Business and Management Strand",
        specializations: [],
      },
      {
        name: "Science, Technology, Engineering, and Mathematics (STEM) Strand",
        specializations: [],
      },
      {
        name: "Humanities and Social Science (HUMSS) Strand",
        specializations: [],
      },
      {
        name: "General Academic Strand (GAS)",
        specializations: [],
      },
    ],
  },
  {
    name: "Arts and Design Track",
    strands: [],
  },
  {
    name: "Sports Track",
    strands: [],
  },
  {
    name: "Technical-Vocational-Livelihood (TVL) Track",
    strands: [
      {
        name: "Agricultural-Fishery Arts (AFA) Strand",
        specializations: [
          { name: "Agricultural Crops Production (NC I)" },
          { name: "Agricultural Crops Production (NC II)" },
          { name: "Agricultural Crops Production (NC III) " },
          { name: "Animal Health Care Management (NC III)" },
          { name: "Animal Production (Poultry-Chicken) (NC II)" },
          { name: "Animal Production (Large Ruminants) (NC II)" },
          { name: "Animal Production (Swine) (NC II)" },
          { name: "Aquaculture (NC II)" },
          { name: "Artificial Insemination (Large Ruminants) (NC II)" },
          { name: "Artificial Insemination (Swine) (NC II) " },
          { name: "Fish Capture (NC II)" },
          { name: "Fishing Gear Repair and Maintenance (NC III)" },
          { name: "Fish-Products Packaging (NC II)" },
          { name: "Fish Wharf Operation (NC I)" },
          { name: "Food Processing (NC II)" },
          { name: "Horticulture (NC III) " },
          { name: "Landscape Installation and Maintenance (NC II)" },
          { name: "Organic Agriculture (NC II)" },
          { name: "Pest Management (NC II)" },
          { name: "Rice Machinery Operations (NC II)" },
          { name: "Rubber Processing (NC II)" },
          { name: "Rubber Production (NC II)" },
          { name: "Slaughtering Operations (Hog/Swine/Pig) (NC II)" },
        ],
      },
      {
        name: "Home Economics (HE) Strand",
        specializations: [
          {
            name: "Attractions and Theme Parks Operations with Ecotourism (NC II)",
          },
          { name: "Barbering (NC II)" },
          { name: "Bartending (NC II)" },
          { name: "Beauty/Nail Care (NC II)" },
          { name: "Bread and Pastry Production (NC II)" },
          { name: "Caregiving (NC II)" },
          { name: "Commercial Cooking (NC III)" },
          { name: "Cookery (NC II)" },
          { name: "Dressmaking (NC II)" },
          { name: "Events Management Services (NC III)" },
          { name: "Fashion Design (Apparel) (NC III)" },
          { name: "Food and Beverage Services (NC II)" },
          { name: "Front Office Services (NC II)" },
          { name: "Hairdressing (NC II)" },
          { name: "Hairdressing (NC III) " },
          { name: "Handicraft (Basketry, Macrame) (Non-NC)" },
          { name: "Handicraft (Fashion Accessories, Paper Craft) (Non-NC)" },
          { name: "Handicraft (Needlecraft) (Non-NC)" },
          { name: "Handicraft (Woodcraft, Leathercraft) (Non-NC)" },
          { name: "Housekeeping (NC II) " },
          { name: "Local Guiding Services (NC II)" },
          { name: "Tailoring (NC II)" },
          { name: "Tourism Promotion Services (NC II)" },
          { name: "Travel Services (NC II)" },
          { name: "Wellness Massage (NC II)" },
        ],
      },
      {
        name: "Industrial Arts (IA) Strand",
        specializations: [
          { name: "Automotive Servicing (NC I)" },
          { name: "Automotive Servicing (NC II)" },
          { name: "Carpentry (NC II)" },
          { name: "Carpentry (NC III)" },
          { name: "Construction Painting (NC II)" },
          {
            name: "Domestic Refrigeration and Air-Conditioning (DOMRAC) Servicing (NC II)",
          },
          { name: "Driving (NC II)	" },
          { name: "Electrical Installation and Maintenance (NC II)" },
          { name: "Electric Power Distribution Line Construction (NC II)" },
          {
            name: "Electronic Products Assembly and Servicing (EPAS) (NC II) ",
          },
          { name: "Furniture Making (Finishing) (NC II)" },
          { name: "Instrumentation and Control Servicing (NC II) 	" },
          { name: "Gas Metal Arc Welding (GMAW) (NC II)" },
          { name: "Gas Tungsten Arc Welding (GTAW) (NC II)" },
          { name: "Machining (NC I)" },
          { name: "Machining (NC II)" },
          { name: "Masonry (NC II)" },
          { name: "Mechatronics Servicing (NC II)" },
          { name: "Motorcycle/Small Engine Servicing (NC II)" },
          { name: "Plumbing (NC I)" },
          { name: "Plumbing (NC II)" },
          {
            name: "Refrigeration and Air-Conditioning  (Packaged Air-Conditioning Unit (PACU)/Commercial Refrigeration Equipment (CRE) Servicing (NC III)",
          },
          { name: "Shielded Metal Arc Welding (SMAW) (NC I)" },
          { name: "Shielded Metal Arc Welding (SMAW) (NC II)" },
          { name: "Tile Setting (NC II)" },
          { name: "Transmission Line Installation and Maintenance (NC II)" },
        ],
      },
      {
        name: "Maritime",
        specializations: [
          { name: "Navigational Watch 1" },
          { name: "Navigational Watch 2" },
          { name: "Navigational Watch 3" },
          { name: "Engine Watch 1" },
          { name: "Engine Watch 2" },
          { name: "Safety 1" },
          { name: "Safety 2" },
          { name: "Ship's Catering Services (NC I)" },
        ],
      },
      {
        name: "Information and Communications Technology (ICT) Strand",
        specializations: [
          { name: "Animation (NC II)" },
          { name: "Broadband Installation (Fixed Wireless Systems) (NC II)" },
          { name: "Computer Programming (.Net Technology) (NC III)" },
          { name: "Computer Programming (Java) (NC III)" },
          { name: "Computer Programming (Oracle Database) (NC III)" },
          { name: "Computer Systems Servicing (NC II)" },
          { name: "Contact Center Services (NC II)" },
          { name: "Illustration (NC II)" },
          { name: "Medical Transcription (NC II)" },
          { name: "Technical Drafting (NC II)" },
          {
            name: "Telecom OSP and Subscriber Line Installation (Copper Cable/POTS and DSL) (NC II)",
          },
          { name: "Telecom OSP Installation (Fiber Optic Cable) (NC II)" },
        ],
      },
    ],
  },
];

export default tracks;
