const tracks = [
  {
    name: "Academic Track",
    strand: [
      {
        name: "Accountancy, Business and Management Strand",
        specialization: [],
      },
      {
        name: "Science, Technology, Engineering, and Mathematics (STEM) Strand",
        specialization: [],
      },
      {
        name: "Humanities and Social Science (HUMSS) Strand",
        specialization: [],
      },
      {
        name: "General Academic Strand (GAS)",
        specialization: [],
      },
    ],
  },
  {
    name: "Arts and Design Track",
    strand: [],
  },
  {
    name: "Sports Track",
    strand: [],
  },
  {
    name: "Technical-Vocational-Livelihood (TVL) Track",
    strand: [
      {
        name: "Agricultural-Fishery Arts (AFA) Strand",
        specialization: [
          "Agricultural Crops Production (NC I)",
          "Agricultural Crops Production (NC II)",
          "Agricultural Crops Production (NC III) ",
          "Animal Health Care Management (NC III)",
          "Animal Production (Poultry-Chicken) (NC II)",
          "Animal Production (Large Ruminants) (NC II)",
          "Animal Production (Swine) (NC II)",
          "Aquaculture (NC II)",
          "Artificial Insemination (Large Ruminants) (NC II)",
          "Artificial Insemination (Swine) (NC II) ",
          "Fish Capture (NC II)",
          "Fishing Gear Repair and Maintenance (NC III)",
          "Fish-Products Packaging (NC II)",
          "Fish Wharf Operation (NC I)",
          "Food Processing (NC II)",
          "Horticulture (NC III) ",
          "Landscape Installation and Maintenance (NC II)",
          "Organic Agriculture (NC II)",
          "Pest Management (NC II)",
          "Rice Machinery Operations (NC II)",
          "Rubber Processing (NC II)",
          "Rubber Production (NC II)",
          "Slaughtering Operations (Hog/Swine/Pig) (NC II)",
        ],
      },
      {
        name: "Home Economics (HE) Strand",
        specialization: [
          "Attractions and Theme Parks Operations with Ecotourism (NC II)",
          "Barbering (NC II)",
          "Bartending (NC II)",
          "Beauty/Nail Care (NC II)",
          "Bread and Pastry Production (NC II)",
          "Caregiving (NC II)",
          "Commercial Cooking (NC III)",
          "Cookery (NC II)",
          "Dressmaking (NC II)",
          "Events Management Services (NC III)",
          "Fashion Design (Apparel) (NC III)",
          "Food and Beverage Services (NC II)",
          "Front Office Services (NC II)",
          "Hairdressing (NC II)",
          "Hairdressing (NC III) ",
          "Handicraft (Basketry, Macrame) (Non-NC)",
          "Handicraft (Fashion Accessories, Paper Craft) (Non-NC)",
          "Handicraft (Needlecraft) (Non-NC)",
          "Handicraft (Woodcraft, Leathercraft) (Non-NC)",
          "Housekeeping (NC II) ",
          "Local Guiding Services (NC II)",
          "Tailoring (NC II)",
          "Tourism Promotion Services (NC II)",
          "Travel Services (NC II)",
          "Wellness Massage (NC II)",
        ],
      },
      {
        name: "Industrial Arts (IA) Strand",
        specialization: [
          "Automotive Servicing (NC I)",
          "Automotive Servicing (NC II)",
          "Carpentry (NC II)",
          "Carpentry (NC III) ",
          "Construction Painting (NC II)",
          "Domestic Refrigeration and Air-Conditioning (DOMRAC) Servicing (NC II)	",
          "Driving (NC II)	",
          "Electrical Installation and Maintenance (NC II)",
          "Electric Power Distribution Line Construction (NC II)",
          "Electronic Products Assembly and Servicing (EPAS) (NC II) ",
          "Furniture Making (Finishing) (NC II)",
          "Instrumentation and Control Servicing (NC II) 	",
          "Gas Metal Arc Welding (GMAW) (NC II)",
          "Gas Tungsten Arc Welding (GTAW) (NC II)	",
          "Machining (NC I)",
          "Machining (NC II)",
          "Masonry (NC II)		",
          "Mechatronics Servicing (NC II) 	",
          "Motorcycle/Small Engine Servicing (NC II)	",
          "Plumbing (NC I)		",
          "Plumbing (NC II)",
          "Refrigeration and Air-Conditioning  (Packaged Air-Conditioning Unit (PACU)/Commercial Refrigeration Equipment (CRE) Servicing (NC III)",
          "Shielded Metal Arc Welding (SMAW) (NC I)",
          "Shielded Metal Arc Welding (SMAW) (NC II) ",
          "Tile Setting (NC II)",
          "Transmission Line Installation and Maintenance (NC II) ",
        ],
      },
      {
        name: "Maritime",
        specialization: [
          "Navigational Watch 1",
          "Navigational Watch 2",
          "Navigational Watch 3",
          "Engine Watch 1",
          "Engine Watch 2",
          "Safety 1",
          "Safety 2",
          "Ship's Catering Services (NC I)",
        ],
      },
      {
        name: "Information and Communications Technology (ICT) Strand",
        specialization: [
          "Animation (NC II)",
          "Broadband Installation (Fixed Wireless Systems) (NC II)",
          "Computer Programming (.Net Technology) (NC III)",
          "Computer Programming (Java) (NC III)",
          "Computer Programming (Oracle Database) (NC III)",
          "Computer Systems Servicing (NC II)",
          "Contact Center Services (NC II)",
          "Illustration (NC II)",
          "Medical Transcription (NC II)",
          "Technical Drafting (NC II)",
          "Telecom OSP and Subscriber Line Installation (Copper Cable/POTS and DSL) (NC II)",
          "Telecom OSP Installation (Fiber Optic Cable) (NC II)",
        ],
      },
    ],
  },
];
